// <auto-generated />
namespace Simple_shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addFieldShortDesc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addFieldShortDesc));
        
        string IMigrationMetadata.Id
        {
            get { return "201710311002254_addFieldShortDesc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
